version: "3"
services:
  api:
    container_name: manu-backend
    build: .
    ports:
      - "8080:8080"
      - "4569:4569"
    volumes:
      - ./.env.example.local:/app/.env
      - ./public/assets:/app/public/assets
      - ./app:/app/app
      - ./config:/app/app/config
