app: manu
service: player
frameworkVersion: '3'
provider:
  name: aws
  runtime: provided.al2
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-2'}
#  httpApi:
#    authorizers:
#      someJwtAuthorizer:
#        type: jwt
#        identitySource: $request.header.Authorization
#        issuerUrl: https://cognito-idp.${region}.amazonaws.com/${cognitoPoolId}
#        audience:
#          - ${client1Id}
#          - ${client2Id}
plugins:
  - ./vendor/bref/bref
  - serverless-domain-manager
  - serverless-dotenv-plugin
functions:
  app:
    handler: 'public/index.php'
    description: ''
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - httpApi: '*'

# Exclude files from deployment
package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'

resources:
  Resources:
    ArchetypeTableResource:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:provider.stage}.player"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  customDomain:
    domainName: api.teclabrava.com
    stage: ${opt:stage, 'dev'}
    basePath: "${self:app}/${opt:stage, 'dev'}/v1"
    createRoute53Record: true
    certificateName: "*.teclabrava.com"
    securityPolicy: tls_1_2
    endpointType: regional
    apiType: http


