app: manu
service: player
frameworkVersion: '3'
provider:
  name: aws
  runtime: provided.al2
  stage: ${opt:stage, 'local'}
  region: ${env:AWS_REGION, 'us-east-2'}
#  httpApi:
#    authorizers:
#      someJwtAuthorizer:
#        type: jwt
#        identitySource: $request.header.Authorization
#        issuerUrl: https://cognito-idp.${region}.amazonaws.com/${cognitoPoolId}
#        audience:
#          - ${client1Id}
#          - ${client2Id}
plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline
functions:
  app:
    handler: 'public/index.php'
    description: 'CRUD operations on the player table'
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-80-fpm}
    events:
      - httpApi: '*'

# Exclude files from deployment
package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'

resources:
  Resources:
    PlayerTableResource:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:provider.stage}.player"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    BucketPlayerData:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${self:provider.stage}-player-data"
custom:
  customDomain:
    domainName: api.teclabrava.com
    stage: ${opt:stage, 'local'}
    basePath: "${self:app}/${opt:stage, 'local'}/v1"
    createRoute53Record: true
    autoDomain: true
    certificateName: "*.teclabrava.com"
    securityPolicy: tls_1_2
    endpointType: regional
    apiType: http
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      player:
        sources:
          - table: "${self:provider.stage}.player"
            sources: [ ./database/seeders/players.json ]
  s3:
    stages:
      - local
    port: 4569
    directory: storage/bucket
