app: manu
service: player
frameworkVersion: '3'
provider:
  name: aws
  runtime: provided.al2
  stage: ${opt:stage, 'local'}
  region: ${env:AWS_REGION, 'us-east-2'}
plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
  - serverless-domain-manager
  - serverless-dotenv-plugin
functions:
  app:
    handler: 'public/index.php'
    description: 'CRUD operations on the player table'
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-80-fpm}
      - ${bref-extra:gd-php-80}
    events:
      - httpApi: '*'
  console:
    description: 'remote command execution'
    timeout: 60
    handler: artisan
    layers:
      - ${bref:layer.php-80}
      - ${bref:layer.console}

# Exclude files from deployment
package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!public/assets'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'

resources:
  Resources:
    PlayerTableResource:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:provider.stage}.player"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: nickname
            AttributeType: S
          - AttributeName: avatar
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: ranking
            AttributeType: N
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: updated_at
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  customDomain:
    domainName: staging.teclabrava.com
    stage: ${opt:stage, 'local'}
    basePath: "${self:app}/${opt:stage, 'local'}/v1"
    createRoute53Record: true
    autoDomain: true
    certificateName: "*.teclabrava.com"
    securityPolicy: tls_1_2
    endpointType: regional
    apiType: http
