app: manu
service: player
frameworkVersion: '3'
provider:
  name: aws
  stage: local
  region: 'us-east-2'
plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-dynamodb-local
package:
  patterns:
    - '!node_modules/**'
    - '!public/storage'
    - '!public/assets'
    - '!resources/assets/**'
    - '!storage/**'
    - '!tests/**'

resources:
  Resources:
    PlayerTableLocal:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: local.player
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: ranking
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 100
          WriteCapacityUnits: 100
        GlobalSecondaryIndexes:
          - IndexName: rankingIndex
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: ranking
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 100
              WriteCapacityUnits: 100
    BucketLocal:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: manu-frontend-local
custom:
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      sharedDb: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      convertEmptyValues: true
  s3:
    stages:
      - local
    port: 4569
    address: '0.0.0.0'
    directory: ./public/assets
