<?php

/**
 * Mañu
 * Mañu es el juego .... [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@teclabrava.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class PlayerApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation addplayer
     *
     * Add a new player to the store.
     *
     *
     * @return Http response
     */
    public function addplayer()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addplayer');
        }
        $body = $input['body'];


        return response('How about implementing addplayer as a post method ?');
    }
    /**
     * Operation updateplayer
     *
     * Update an existing player.
     *
     *
     * @return Http response
     */
    public function updateplayer()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateplayer');
        }
        $body = $input['body'];


        return response('How about implementing updateplayer as a put method ?');
    }
    /**
     * Operation findplayersByStatus
     *
     * Finds players by status.
     *
     *
     * @return Http response
     */
    public function findplayersByStatus()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['status'])) {
            throw new \InvalidArgumentException('Missing the required parameter $status when calling findplayersByStatus');
        }
        $status = $input['status'];


        return response('How about implementing findplayersByStatus as a get method ?');
    }
    /**
     * Operation findplayersByTags
     *
     * Finds players by tags.
     *
     *
     * @return Http response
     */
    public function findplayersByTags()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['tags'])) {
            throw new \InvalidArgumentException('Missing the required parameter $tags when calling findplayersByTags');
        }
        $tags = $input['tags'];


        return response('How about implementing findplayersByTags as a get method ?');
    }
    /**
     * Operation deleteplayer
     *
     * Deletes a player.
     *
     * @param int $player_id player id to delete (required)
     *
     * @return Http response
     */
    public function deleteplayer($player_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteplayer as a delete method ?');
    }
    /**
     * Operation getplayerById
     *
     * Find player by ID.
     *
     * @param int $player_id ID of player to return (required)
     *
     * @return Http response
     */
    public function getplayerById($player_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getplayerById as a get method ?');
    }
    /**
     * Operation updateplayerWithForm
     *
     * Updates a player in the store with form data.
     *
     * @param int $player_id ID of player that needs to be updated (required)
     *
     * @return Http response
     */
    public function updateplayerWithForm($player_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateplayerWithForm as a post method ?');
    }
    /**
     * Operation uploadFile
     *
     * uploads an image.
     *
     * @param int $player_id ID of player to update (required)
     *
     * @return Http response
     */
    public function uploadFile($player_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing uploadFile as a post method ?');
    }
}
