name: Deployment Serverless
on:
  push:
    branches:
      - 'main'
      - 'develop'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env

    - name: Run Testsuite
      run: vendor/bin/phpunit tests/

    - name: Deployment in AWS
      run: |
        npm install -g serverless
        cd ${{ github.workdir }}
        serverless deploy --stage ${GITHUB_REF##*/}

