name: Deployment Serverless
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g serverless
      - run: serverless config credentials.aws set --stage $AWS_STAGE --region $AWS_REGION --accessKeyId $AWS_ACCESS_KEY_ID --secretAccessKey $AWS_SECRET_ACCESS_KEY
      - run: serverless deploy

