name: Test Unit
on: [push,pull_request]
jobs:
  test-unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run PHPUnit tests
        run: |
          cd src/
          composer install
          vendor/bin/phpunit
