name: Deployment Serverless
on: [push]
jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5 # or alternative dependency management
      - uses: php-actions/phpunit@v3
      - name: Run PHPUnit tests
        uses: php-actions/phpunit@v3
        run: |
          cd src/
          composer install
          phpunit
